:: Uncomment the '@unittest.skip' annotation from test class 'AccessManagerClientIntegrationTests'
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.test_connection_exceptions
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.test_send_get_request_value_error
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.test_send_get_request_element_not_found_error
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.tests_url_reserved_characters
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.test_property_gets_on_empty_access_manager
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.test_add_elements_and_mappings
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.test_queries
python -m unittest src.tests.access_manager_client_integration_tests.AccessManagerClientIntegrationTests.test_remove_elements_and_mappings
python -m unittest src.tests.access_manager_string_element_client_integration_tests
